//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariablePoint
    {
        public int VariableID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public string EngUnits { get; set; }
        public Nullable<short> ForecastID { get; set; }
        public Nullable<bool> Good { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Name { get; set; }
        public Nullable<float> Value { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> VariableMasterID { get; set; }
        public Nullable<int> VariableTypeID { get; set; }
        public string Tag { get; set; }
    }
}
