//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableMaster
    {
        public int VariableMasterID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PlantObjectTypeID { get; set; }
        public string ObjectGroupID { get; set; }
        public string CharSearch { get; set; }
    }
}
