//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForecastAppDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeMaster
    {
        public int Attribute_Master_ID { get; set; }
        public string LongName { get; set; }
        public Nullable<int> VariableMasterID { get; set; }
        public Nullable<int> BlockEnhancementID { get; set; }
        public string TextBoxControl { get; set; }
        public string ComboBoxControl { get; set; }
        public Nullable<int> LookUpTable { get; set; }
        public string Mandatory { get; set; }
        public Nullable<int> PlantObjectTypeID { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> ObjectGroupID { get; set; }
        public string ComboBoxContent { get; set; }
    }
}
