//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForecastAppDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastMapping
    {
        public int ForecastMappingID { get; set; }
        public Nullable<int> ForecastTypeID { get; set; }
        public Nullable<int> VariableMasterID { get; set; }
        public Nullable<bool> Mandatory { get; set; }
    }
}
