//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForecastAppDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastSelection
    {
        public int SelectionID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<int> BlockID { get; set; }
        public string ForecastMasterByBlockType { get; set; }
        public string BlockEnhancements { get; set; }
        public string TrainID { get; set; }
        public string Criteria { get; set; }
    }
}
