//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForecastAppDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generator
    {
        public int GeneratorID { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public int SiteID { get; set; }
        public int BlockID { get; set; }
        public Nullable<int> GasTurbineID { get; set; }
        public Nullable<int> SteamTurbineID { get; set; }
    }
}
