//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForecastAppDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTTypeUniquePlantMasterVariable
    {
        public int GasTurbineTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlantMasterVariableID { get; set; }
        public string Mandatory { get; set; }
    }
}
