//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForecastAppDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiSnapshot
    {
        public string Tag { get; set; }
        public string Descriptor { get; set; }
        public Nullable<double> Value { get; set; }
        public string EngUnits { get; set; }
        public Nullable<double> Status { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string PointType { get; set; }
    }
}
