//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForecastAppDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int SiteID { get; set; }
        public string Acronym { get; set; }
        public float Elevation { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string Timezone { get; set; }
        public Nullable<bool> UseMetricUnits { get; set; }
        public string DataDirectory { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Interval { get; set; }
        public string Duration { get; set; }
        public string ArchiveInterval { get; set; }
        public string Archive_Duration { get; set; }
        public string Grid_Frequency { get; set; }
        public string Heat_Rate_Units { get; set; }
        public string Heat_Rate_Calculation { get; set; }
    }
}
