//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForecastAppDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WizardDatabaseEntities : DbContext
    {
        public WizardDatabaseEntities()
            : base("name=WizardDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<Condenser> Condensers { get; set; }
        public virtual DbSet<Forecast> Forecasts { get; set; }
        public virtual DbSet<ForecastMapping> ForecastMappings { get; set; }
        public virtual DbSet<ForecastType> ForecastTypes { get; set; }
        public virtual DbSet<GasTurbine> GasTurbines { get; set; }
        public virtual DbSet<Generator> Generators { get; set; }
        public virtual DbSet<HRSG> HRSGs { get; set; }
        public virtual DbSet<ObjectGroup> ObjectGroups { get; set; }
        public virtual DbSet<PlantObjectType> PlantObjectTypes { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SteamTurbine> SteamTurbines { get; set; }
        public virtual DbSet<TrainMapping> TrainMappings { get; set; }
        public virtual DbSet<VariableMaster> VariableMasters { get; set; }
        public virtual DbSet<VariableMasterMapping> VariableMasterMappings { get; set; }
        public virtual DbSet<VariablePoint> VariablePoints { get; set; }
        public virtual DbSet<PiSnapshot> PiSnapshots { get; set; }
        public virtual DbSet<AttributeMaster> AttributeMasters { get; set; }
        public virtual DbSet<ForecastSelection> ForecastSelections { get; set; }
        public virtual DbSet<GTTypeUniquePlantMasterVariable> GTTypeUniquePlantMasterVariables { get; set; }
        public virtual DbSet<PlantMasterVariable> PlantMasterVariables { get; set; }
        public virtual DbSet<PossiblePlantMasterVariable> PossiblePlantMasterVariables { get; set; }
    }
}
