//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RTP_ForecastDatabaseEntities : DbContext
    {
        public RTP_ForecastDatabaseEntities()
            : base("name=RTP_ForecastDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<Forecast> Forecasts { get; set; }
        public virtual DbSet<ForecastType> ForecastTypes { get; set; }
        public virtual DbSet<ForecastValue> ForecastValues { get; set; }
        public virtual DbSet<GasTurbine> GasTurbines { get; set; }
        public virtual DbSet<Generator> Generators { get; set; }
        public virtual DbSet<HRSG> HRSGs { get; set; }
        public virtual DbSet<InletAirCooling> InletAirCoolings { get; set; }
        public virtual DbSet<Mapping> Mappings { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SteamTurbine> SteamTurbines { get; set; }
        public virtual DbSet<VariableList> VariableLists { get; set; }
        public virtual DbSet<VariableSnapShot> VariableSnapShots { get; set; }
        public virtual DbSet<VariableStandard> VariableStandards { get; set; }
        public virtual DbSet<VariableType> VariableTypes { get; set; }
        public virtual DbSet<XYLUT> XYLUTs { get; set; }
        public virtual DbSet<XYLUTValue> XYLUTValues { get; set; }
    }
}
