//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastValue
    {
        public int ForecastID { get; set; }
        public Nullable<System.DateTimeOffset> Timestamp { get; set; }
        public Nullable<float> Value { get; set; }
        public Nullable<bool> Good { get; set; }
    }
}
