//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRSG
    {
        public int ObjectID { get; set; }
        public Nullable<float> DuctBurnFuelMaxRate { get; set; }
        public Nullable<float> DuctBurnMaxMWGain { get; set; }
        public Nullable<float> COEmissionsLimit { get; set; }
        public Nullable<float> NormalizedLoadMax { get; set; }
        public Nullable<float> NormalizedLoadMin { get; set; }
        public Nullable<float> NOXEmissionsLimit { get; set; }
    }
}
