//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InletAirCooling
    {
        public int ObjectID { get; set; }
        public Nullable<float> MinTempOn { get; set; }
        public Nullable<float> MinHumidityOn { get; set; }
        public Nullable<int> CoolingTypeID { get; set; }
    }
}
