//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public int BlockID { get; set; }
        public Nullable<int> PlantObjectID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<int> TrainID { get; set; }
        public string Alias { get; set; }
    }
}
