//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableList
    {
        public int VariableID { get; set; }
        public string Tag { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public string EngUnits { get; set; }
        public Nullable<int> StandardVariableID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public Nullable<int> PlantObjectID { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<float> MinValue { get; set; }
        public Nullable<float> MaxValue { get; set; }
        public Nullable<float> DefaultValue { get; set; }
        public Nullable<int> ForecastID { get; set; }
        public Nullable<bool> Archived { get; set; }
    }
}
