//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableStandard
    {
        public int StandardVariableID { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public Nullable<int> VariableTypeID { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<int> PlantObjectID { get; set; }
    }
}
