//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XYLUT
    {
        public int XYLUTID { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public Nullable<int> XAxisVariableID { get; set; }
        public Nullable<int> YAxisVariableID { get; set; }
    }
}
