//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XYLUTValue
    {
        public int XYLUTID { get; set; }
        public Nullable<float> Xvalue { get; set; }
        public Nullable<float> Yvalue { get; set; }
    }
}
