//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condenser
    {
        public int CondenserID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public Nullable<byte> CoolingType { get; set; }
    }
}
