//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasTurbine
    {
        public int GasTurbineID { get; set; }
        public string GasTurbineType { get; set; }
        public int BlockID { get; set; }
        public int SiteID { get; set; }
        public string Acronym { get; set; }
        public string Name { get; set; }
    }
}
