//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainMapping
    {
        public int MappingID { get; set; }
        public int BlockTypeID { get; set; }
        public int TrainID { get; set; }
        public int GasTurbineID { get; set; }
        public int HRSGID { get; set; }
        public int SteamTurbineID { get; set; }
        public int CondenserID { get; set; }
        public int GeneratorID { get; set; }
    }
}
