//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayObject
    {
        public int DisplayID { get; set; }
        public byte Row { get; set; }
        public byte Column { get; set; }
        public Nullable<byte> RowSpan { get; set; }
        public Nullable<byte> ColumnSpan { get; set; }
        public int DisplayObjectID { get; set; }
        public byte DisplayObjectTypeID { get; set; }
    }
}
