//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngUnitsConversion
    {
        public string VariableType { get; set; }
        public byte VariableTypeID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<double> Offset { get; set; }
        public double Scaling { get; set; }
        public string Operation { get; set; }
    }
}
