//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterTimeRange
    {
        public int FilterID { get; set; }
        public Nullable<System.DateTimeOffset> Start { get; set; }
        public Nullable<System.DateTimeOffset> Finish { get; set; }
        public byte Position { get; set; }
    }
}
