//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public short ForecastID { get; set; }
        public byte SiteID { get; set; }
        public byte BlockID { get; set; }
        public int VariableID { get; set; }
        public byte ForecastTypeID { get; set; }
        public string Acronym { get; set; }
        public string Name { get; set; }
        public Nullable<byte> LoadIndex { get; set; }
    }
}
