//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class InletCoolingTypeAlia
    {
        public byte InletCoolingTypeID { get; set; }
        public byte UserID { get; set; }
        public string Acronym { get; set; }
        public string Name { get; set; }
    }
}
