//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitVariable
    {
        public short UnitVariableID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string VariableType { get; set; }
        public byte VariableTypeID { get; set; }
    }
}
