//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public byte BlockID { get; set; }
        public string Alias { get; set; }
        public byte SiteID { get; set; }
        public string Name { get; set; }
        public string DataServer { get; set; }
        public short Port { get; set; }
        public string FileLocation { get; set; }

        //Block Attributes
        public string BlockType { get; set; }
        public bool InletAirCoolingCheck { get; set; }
        public bool InletAirHeatingCheck { get; set; }
        public bool PeakFiringCheck { get; set; }
        public bool SteamInjectionCheck { get; set; }
        public bool DuctBurnersCheck { get; set; }

        public bool HOLForecastCheck { get; set; }

        public bool LOLForecastCheck { get; set; }

        public bool CompressorMapCheck { get; set; }

        public bool TESCheck { get; set; }

        public string ConfigureUnitComboBox { get; set; }

        
    }
}
