//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartFormat
    {
        public int ChartID { get; set; }
        public Nullable<int> BackgroundColor { get; set; }
        public Nullable<bool> MajorGrid { get; set; }
        public Nullable<bool> MinorGrid { get; set; }
        public Nullable<int> Interval { get; set; }
    }
}
