//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastValue
    {
        public short ForecastID { get; set; }
        public System.DateTimeOffset Timestamp { get; set; }
        public float Value { get; set; }
        public bool Good { get; set; }
    }
}
