//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridHealthCheck
    {
        public int GridID { get; set; }
        public byte Position { get; set; }
        public int HealthCheckID { get; set; }
        public byte Decimals { get; set; }
        public byte Alpha { get; set; }
        public byte Red { get; set; }
        public byte Green { get; set; }
        public byte Blue { get; set; }
        public byte Size { get; set; }
        public bool Bold { get; set; }
        public bool Italic { get; set; }
    }
}
