//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCheck
    {
        public int HealthCheckID { get; set; }
        public byte UserID { get; set; }
        public string Name { get; set; }
        public int ModelID { get; set; }
        public float Actual { get; set; }
        public float Predicted { get; set; }
        public byte Comparison { get; set; }
        public float Threshold { get; set; }
        public string EngUnits { get; set; }
        public int Duration { get; set; }
        public int AlertCount { get; set; }
        public int NormalCount { get; set; }
        public bool AlertStatus { get; set; }
        public int MessageID { get; set; }
        public Nullable<bool> Good { get; set; }
        public Nullable<System.DateTimeOffset> Timestamp { get; set; }
        public bool Visible { get; set; }
        public Nullable<System.DateTimeOffset> LastModified { get; set; }
        public string Abbreviation { get; set; }
        public int FilterID { get; set; }
    }
}
