//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCheckCompare
    {
        public int HealthCheckID { get; set; }
        public int ModelVariableID { get; set; }
        public int CompareVariableID { get; set; }
    }
}
