//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayoutPanelObject
    {
        public int LayoutPanelObjectID { get; set; }
        public int LayoutPanelID { get; set; }
        public string HeaderText { get; set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }
        public byte Rows { get; set; }
        public byte Columns { get; set; }
        public byte BorderStyle { get; set; }
    }
}
