//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelInputCoeff
    {
        public int ModelID { get; set; }
        public int VariableID { get; set; }
        public byte Power { get; set; }
        public double Value { get; set; }
    }
}
