//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantObjectType
    {
        public byte PlantObjectTypeID { get; set; }
        public string Acronym { get; set; }
        public string Name { get; set; }
        public string Table { get; set; }
        public string AliasTable { get; set; }
        public string VariableTable { get; set; }
        public string VariableAliasTable { get; set; }
        public string ReadingTable { get; set; }
    }
}
