//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExpt
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariablePointTemp
    {
        public int VariableID { get; set; }
        public string Name { get; set; }
        public string EngUnits { get; set; }
        public short VariableTypeID { get; set; }
        public short VariableMasterID { get; set; }
        public string Tag { get; set; }
        public short SiteID { get; set; }
        public byte BlockID { get; set; }
        public byte PlantObjectID { get; set; }
        public short PlantObjectTypeID { get; set; }
        public byte SourceID { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public short ForecastID { get; set; }
        public Nullable<System.DateTimeOffset> Timestamp { get; set; }
        public Nullable<float> Value { get; set; }
        public Nullable<bool> Good { get; set; }
    }
}
