//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstRTPForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartVariable
    {
        public int ChartID { get; set; }
        public byte Axis { get; set; }
        public byte Position { get; set; }
        public int VariableID { get; set; }
        public byte VariableIDType { get; set; }
        public byte LineType { get; set; }
        public byte Alpha { get; set; }
        public byte Red { get; set; }
        public byte Green { get; set; }
        public byte Blue { get; set; }
        public bool Dashed { get; set; }
        public byte Size { get; set; }
    }
}
