//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstRTPForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int FilterID { get; set; }
        public byte UserID { get; set; }
        public string Name { get; set; }
        public int MaxRows { get; set; }
        public Nullable<bool> Relative { get; set; }
        public Nullable<int> Start { get; set; }
        public Nullable<int> Finish { get; set; }
        public Nullable<System.DateTimeOffset> LastModified { get; set; }
    }
}
