//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstRTPForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCheckReading
    {
        public int HealthCheckID { get; set; }
        public float Actual { get; set; }
        public float Predicted { get; set; }
        public byte Comparison { get; set; }
        public float Threshold { get; set; }
        public bool AlertStatus { get; set; }
        public System.DateTimeOffset Timestamp { get; set; }
        public bool Good { get; set; }
    }
}
