//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstRTPForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayoutPanelObjectVariable
    {
        public int LayoutPanelObjectID { get; set; }
        public int LayoutPanelID { get; set; }
        public int VariableID { get; set; }
        public int ModelID { get; set; }
        public string Text { get; set; }
        public byte Alignment { get; set; }
        public byte Row { get; set; }
        public byte Column { get; set; }
        public byte Size { get; set; }
    }
}
