//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstRTPForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        public short SummaryID { get; set; }
        public byte SiteID { get; set; }
        public byte BlockID { get; set; }
        public int VariableID { get; set; }
        public int Interval { get; set; }
        public string Name { get; set; }
    }
}
