//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstRTPForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryValue
    {
        public short SummaryID { get; set; }
        public float Average { get; set; }
        public float Maximum { get; set; }
        public float Minimum { get; set; }
        public System.DateTimeOffset Start { get; set; }
        public System.DateTimeOffset Finish { get; set; }
    }
}
